modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Surface%20Mushrooms"
logoFile="icon.png"

[[mods]]
modId="surfacemushrooms"
version="3.1"
displayName="Surface Mushrooms"
displayURL="https://curseforge.com/minecraft/mc-mods/surface-mushrooms"
authors="Rick South"
description='''Mushrooms can be placed on the surface in daylight and in any brightness.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.surfacemushrooms]]
    modId="collective"
    mandatory=true
    versionRange="[6.56,)"
    ordering="NONE"
    side="BOTH"